//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int ClienteID { get; set; }
        public string Documento { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> TipoClienteID { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual TipoCliente TipoCliente { get; set; }
    }
}
