//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_VENTA
    {
        public int DetalleVentaID { get; set; }
        public Nullable<int> VentaID { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public Nullable<int> MedicamentoID { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual MEDICAMENTO MEDICAMENTO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual VENTA VENTA { get; set; }
    }
}
