//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentosModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicamentosModel()
        {
            this.MedicamentosLotesModel = new HashSet<MedicamentosLotesModel>();
            this.VentasModel = new HashSet<VentasModel>();
            this.MedicamentosProveedoresModel = new HashSet<MedicamentosProveedoresModel>();
        }
    
        public int MedicamentoID { get; set; }
        public Nullable<int> EstanteID { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<int> CodigoID { get; set; }
    
        public virtual CategoriasModel CategoriasModel { get; set; }
        public virtual CodigosDeBarrasModel CodigosDeBarrasModel { get; set; }
        public virtual EstantesModel EstantesModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicamentosLotesModel> MedicamentosLotesModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentasModel> VentasModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicamentosProveedoresModel> MedicamentosProveedoresModel { get; set; }
    }
}
