//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentosDetalle
    {
        public int Lote { get; set; }
        public string Medicamento { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Vencimiento { get; set; }
        public string Categoria { get; set; }
        public string Estante { get; set; }
        public string Sector { get; set; }
        public int NumEstante { get; set; }
    }
}
