//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductosModel()
        {
            this.VentasModel = new HashSet<VentasModel>();
        }
    
        public int ProductoID { get; set; }
        public string NombreProducto { get; set; }
        public string DescripcionProducto { get; set; }
        public decimal PrecioUnitario { get; set; }
        public Nullable<int> EstanteID { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public Nullable<int> CodigoID { get; set; }
    
        public virtual CategoriasModel CategoriasModel { get; set; }
        public virtual CodigosDeBarrasModel CodigosDeBarrasModel { get; set; }
        public virtual EstantesModel EstantesModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentasModel> VentasModel { get; set; }
    }
}
