//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasModel
    {
        public int VentaID { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public Nullable<int> MedicamentoID { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaVenta { get; set; }
    
        public virtual MedicamentosModel MedicamentosModel { get; set; }
        public virtual ProductosModel ProductosModel { get; set; }
    }
}
