//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaInventarioMedicamento
    {
        public string Codigo { get; set; }
        public string Lote { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Vencimiento { get; set; }
        public string Categoria { get; set; }
        public string Nombre_estante { get; set; }
        public string Sector { get; set; }
        public int Numero_estante { get; set; }
    }
}
