//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaInventario
    {
        public string Codigo_de_Barras { get; set; }
        public string Nombre_Medicamento { get; set; }
        public string Descripcion_Medicamento { get; set; }
        public int Stock { get; set; }
        public Nullable<System.DateTime> Fecha_de_Vencimiento { get; set; }
        public string Nombre_Categoria { get; set; }
        public string Nombre_de_Estante { get; set; }
        public string Sector_de_Estante { get; set; }
        public int Numero_de_Estante { get; set; }
        public string Nombre_Proveedor { get; set; }
    }
}
