//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaInventario
    {
        public string Cod_ { get; set; }
        public string Lote { get; set; }
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
        public Nullable<System.DateTime> VTO { get; set; }
        public string Estante { get; set; }
        public string Sector { get; set; }
        public int Num__Estante { get; set; }
        public string Categoría { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public string Proveedor { get; set; }
    }
}
