//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentosModel
    {
        public int LoteID { get; set; }
        public Nullable<int> EstanteID { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
    
        public virtual CategoriasModel CategoriasModel { get; set; }
        public virtual EstantesModel EstantesModel { get; set; }
        public virtual LotesModel LotesModel { get; set; }
    }
}
