//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaGestionFarmaceuticaEntities : DbContext
    {
        public SistemaGestionFarmaceuticaEntities()
            : base("name=SistemaGestionFarmaceuticaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriasModel> CategoriasModel { get; set; }
        public virtual DbSet<EstantesModel> EstantesModel { get; set; }
        public virtual DbSet<LotesModel> LotesModel { get; set; }
        public virtual DbSet<MedicamentosModel> MedicamentosModel { get; set; }
    }
}
